spring:
  profile.active: dev, test, prod
  datasource:
    url: jdbc:mysql://localhost:3306/salud_vital
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: salud_vital
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true




server:
  error:
    include-stacktrace: never
api:
  security:
    secret: ${JWT_SECRET:123456}


